development:
  adapter: async
  url: localhost:6379
  channel_prefix: CableChat_dev

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: CableChat_production
